[project]
name = "gladiaio-sdk"
version = "0.2.10"
description = "Gladia SDK for Python"
requires-python = ">=3.10,<4"
readme = "README.md"
dependencies = [
  "dataclasses-json>=0.6.0",
  "httpx>=0.28.0",
  "pyee>=13.0.0",
  "websockets>=15.0.0"
]

[dependency-groups]
dev = [
  "autopep8>=2.3.1",
  "ruff>=0.8.2",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0"
]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [ "src/gladiaio_sdk" ]

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 100
indent-width = 2

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "standard"
