name: Publish

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Target project to publish'
        type: choice
        required: true
        options:
          - sdk-js
          - sdk-python
      dry-run:
        description: 'Dry run (no publish)'
        type: boolean
        required: false
        default: false
  push:
    tags:
      - 'sdk-*@*'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false
      - run: npm install -g npm
      - run: bun install

      - name: Determine project
        id: determine-project
        run: |
          if [ -n "${{ github.event.inputs.project }}" ]; then
            PROJECT="${{ github.event.inputs.project }}"
          else
            REF="${{ github.ref_name }}" # e.g. sdk-js@0.5.2
            PROJECT="${REF%%@*}"       # keeps left side of '@'
          fi
          echo "PROJECT=$PROJECT" >> "$GITHUB_ENV"
          echo "Publishing $PROJECT"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python deps
        run: bun nx run-many -t sync

      - name: Build ${{ env.PROJECT }}
        run: bun nx run-many -t build -p "$PROJECT"

      - name: Publish ${{ env.PROJECT }}
        run: |
          bun run publish -- \
            --projects "$PROJECT" \
            $([ "${{ github.event.inputs['dry-run'] }}" = "true" ] && echo --dryRun || true)
