name: Release

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Target project to release'
        type: choice
        required: false
        options:
          - ''
          - sdk-js
          - sdk-python
        default: ''
      version:
        description: 'Version bump type'
        type: choice
        required: false
        options:
          - ''
          - major
          - minor
          - patch
        default: ''
      first-release:
        description: 'Is this the first release?'
        type: boolean
        required: false
        default: false
      dry-run:
        description: 'Dry run (no changes pushed)'
        type: boolean
        required: false
        default: false

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - name: Fetch 1password key
        id: secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          SDK_PUBLISHER_PRIVATE_KEY: op://infra_automation/sdkreleasemanager/private key
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SA_TOKEN_INFRA_AUTOMATION }}

      - name: Generate a token
        id: generate-token-sdk-publisher
        uses: actions/create-github-app-token@v1
        with:
          app-id: '2089066'
          private-key: ${{ steps.secrets.outputs.SDK_PUBLISHER_PRIVATE_KEY }}
          owner: 'gladiaio'
          repositories: 'sdk'

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token-sdk-publisher.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token-sdk-publisher.outputs.token }}

      - run: |
          git config --global user.name '${{ steps.generate-token-sdk-publisher.outputs.app-slug }}'
          git config --global user.email '${{ steps.generate-token-sdk-publisher.outputs.app-slug }}@gladia.io'

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token-sdk-publisher.outputs.token }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          package-manager-cache: false
      - run: npm install -g npm
      - run: bun install

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python deps
        run: bun nx run-many -t sync

      - name: Make the release
        id: release
        run: |
          bun run release -- --verbose \
            $([ -n "${{ github.event.inputs.project }}" ] && echo --projects "${{ github.event.inputs.project }}" || true) \
            $([ -n "${{ github.event.inputs.version }}" ] && echo --specifier "${{ github.event.inputs.version }}" || true) \
            $([ "${{ github.event.inputs['first-release'] }}" = "true" ] && echo --firstRelease || true) \
            $([ "${{ github.event.inputs['dry-run'] }}" = "true" ] && echo --dryRun || true)

      - name: Push the commit and tags
        run: git push --follow-tags
